// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU4hA9tQhpOBVJkZbAwU1CKz-Wb8a2dfw',
    appId: '1:74781106008:web:640ee0c9c42e235ad80f2d',
    messagingSenderId: '74781106008',
    projectId: 'plantacoes-b58ef',
    authDomain: 'plantacoes-b58ef.firebaseapp.com',
    storageBucket: 'plantacoes-b58ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhpIbJUMYVyhHWJZzoHsZrlCPfI-odMYU',
    appId: '1:74781106008:android:afea0040147ec150d80f2d',
    messagingSenderId: '74781106008',
    projectId: 'plantacoes-b58ef',
    storageBucket: 'plantacoes-b58ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcENTpMOn2sCrtxZda1-LkVnYkxC3Ys9U',
    appId: '1:74781106008:ios:760a3c6b9a982b60d80f2d',
    messagingSenderId: '74781106008',
    projectId: 'plantacoes-b58ef',
    storageBucket: 'plantacoes-b58ef.appspot.com',
    iosClientId: '74781106008-la3hd64emd93vu7ba51vu9i49ljn4niv.apps.googleusercontent.com',
    iosBundleId: 'br.com.meupacote.gerenciamento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcENTpMOn2sCrtxZda1-LkVnYkxC3Ys9U',
    appId: '1:74781106008:ios:8c7cb08fbe9333b5d80f2d',
    messagingSenderId: '74781106008',
    projectId: 'plantacoes-b58ef',
    storageBucket: 'plantacoes-b58ef.appspot.com',
    iosClientId: '74781106008-0k1eff0oc553qupi5n83or0ou17sol7k.apps.googleusercontent.com',
    iosBundleId: 'br.com.meupacote.gerenciamento.RunnerTests',
  );
}
